### PR TITLE
Remove cyclic dependency with Products.CMFPlone.

### LINKED ISSUE #37: Cyclic dependency with Products.CMFPlone
Ref: plone/Products.CMFPlone#3304

### PR DESCRIPTION
**Pull request by ericof**
Fixes #37

### CODE REVIEW

**Comment by ericof** [comment]
@jenkins-plone-org please run jobs

**Comment by ericof** [comment]
@mauritsvanrees Why do we have a CircleCI integration here?

**Review by mauritsvanrees — APPROVED** [review]
LGTM.

I have disabled the CircleCI check now, which was only ever active on a single branch, see also https://github.com/plone/plone.app.contentlisting/pull/32

**Comment by gforcada** [comment]
Removing entries on setup.py is fine to avoid the installation problem 👍🏾 there are still circular imports to be resolved, and that's a huuuuge task to address 😓 if you search for `CMFPlone` on this distribution you will find a few references.

We could ignore them and say that if you install `p.a.contentlisting` you need of course CMFPlone, but the circular imports can show/hide other side effects 😖

**Comment by ericof** [comment]
@gforcada I do agree with you. and a proper solution is way more complex than this. But, for now, this will do (and in the long run, merging packages and properly addressing the requirements of each one)

**Pull request merged**
