### PR TITLE
Minor refactoring for Python 3 compatibility

### PR DESCRIPTION
**Pull request by hvelarde**

### CODE REVIEW

**Comment by hvelarde** [comment]
@plone/framework-team please review.

**Comment by hvelarde** [comment]
I have no idea why this is failing.

**Comment by hvelarde** [comment]
this seems to be zope.interface fault:

https://github.com/zopefoundation/zope.interface/blob/4.5.0/src/zope/interface/common/sequence.py#L34-L38

we need to remove `__getitem__` from there also.

**Comment by jensens** [comment]
cc @pbauer

**Comment by gforcada** [comment]
@pbauer as you are more into the python3... I was fixing a test failure in plone.app.querystring that lead me to the commit I made here in this branch.

With my commit and without @hvelarde commit both p.a.querystring and p.a.contentlisting tests passes (circa one test that fails anyway in p.a.contentlisting). With @hvelarde and my commits there are 5 test failures.

@hvelarde which tests where you trying to fix? :thinking:

**Comment by hvelarde** [comment]
@gforcada I'm using a different approach to achieve Python 3 compatibility (using `pylint --py3k` to find issues in our code); as mentioned in the code itself `__getslice__` has been deprecated since Python 2.0 and we need to remove it.

**Pull request merged**
