### PR TITLE
Do not throw an error if the contenttype is not in the mimetyes_registry

### PR DESCRIPTION
**Pull request by tschorr**
Same problem as https://github.com/plone/plone.app.portlets/pull/129

### CODE REVIEW

**Comment by tschorr** [comment]
@jenkins-plone-org please run jobs

**Comment by tschorr** [comment]
@jenkins-plone-org please run jobs

**Comment by tschorr** [comment]
The failing robot tests look unrelated.

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by tschorr** [comment]
Can we have a PyPI release? Who can do this?

**Comment by jensens** [comment]
release can be done by @mauritsvanrees

**Comment by mauritsvanrees** [comment]
I have released `plone.app.contentlisting` 2.0.6.

**Comment by tschorr** [comment]
> I have released `plone.app.contentlisting` 2.0.6.

Thank you!

**Pull request merged**
