### PR TITLE
 Introduce ``@@contentlisting`` with Collection support (Plone 4.3)

### PR DESCRIPTION
**Pull request by thet**
Support for listing contents for plone.app.contenttypes based collections.
See the original pull request for Plone 5: https://github.com/plone/plone.app.contentlisting/pull/6

### CODE REVIEW

**Comment by pbauer** [comment]
http://jenkins.plone.org/job/pull-request-4.3/77/

**Comment by thet** [comment]
i'm not sure, if we should include that in plone 4.3... i used it in 4.3, but added the necessary view just in my project itself.
what's your opinion, @pbauer ?

**Comment by jensens** [comment]
looks like we dont want it in 4.3 - in any case if you plan to work on it for 4.3 please just reopen

**Comment by thet** [comment]
Looking at the Changelog it looks like this package is compatible with Plone 4 anyways. Or can be made compatible without much effort.

**Pull request closed without merging**
