### PR TITLE
Plip1734thumbs

### PR DESCRIPTION
**Pull request by fgrcon**
provide Mimetype icon path for file types in contentlisting object
 https://github.com/plone/Products.CMFPlone/issues/173

### CODE REVIEW

**Comment by fgrcon** [comment]
What the hell is going on ?  I checked  http://docs.plone.org/develop/styleguide/python.html ran isort accordingly  .... but  ????

**Comment by gforcada** [comment]
@fgrcon did you have an .isort.cfg file? If not isort sorts the files in a totally different style, see http://jenkinsploneorg.readthedocs.io/en/latest/run-qa-on-package.html for what mr.roboto is actually doing

**Comment by fgrcon** [comment]
@gforcada: Thanks for the hint, but I had done correctly afaik .  But following the instructions ... and:

> root@debian:/usr/local/p5dev/2buildout/src/plone.app.contentlisting# isort -rc -c -vb -sp /usr/local/p5dev/2buildout/src/plone.app.contentlisting/.isort.cfg plone/
> SUCCESS: /usr/local/p5dev/2buildout/src/plone.app.contentlisting/plone/__init__.py Everything Looks Good!
> SUCCESS: /usr/local/p5dev/2buildout/src/plone.app.contentlisting/plone/app/__init__.py Everything Looks Good!
> SUCCESS: /usr/local/p5dev/2buildout/src/plone.app.contentlisting/plone/app/contentlisting/__init__.py Everything Looks Good!
> SUCCESS: /usr/local/p5dev/2buildout/src/plone.app.contentlisting/plone/app/contentlisting/interfaces.py Everything Looks Good!
> SUCCESS: /usr/local/p5dev/2buildout/src/plone.app.contentlisting/plone/app/contentlisting/catalog.py Everything Looks Good!
> SUCCESS: /usr/local/p5dev/2buildout/src/plone.app.contentlisting/plone/app/contentlisting/contentlisting.py Everything Looks Good!
> SUCCESS: /usr/local/p5dev/2buildout/src/plone.app.contentlisting/plone/app/contentlisting/realobject.py Everything Looks Good!
> SUCCESS: /usr/local/p5dev/2buildout/src/plone.app.contentlisting/plone/app/contentlisting/browser.py Everything Looks Good!
> SUCCESS: /usr/local/p5dev/2buildout/src/plone.app.contentlisting/plone/app/contentlisting/tests/__init__.py Everything Looks Good!
> SUCCESS: /usr/local/p5dev/2buildout/src/plone.app.contentlisting/plone/app/contentlisting/tests/test_integration_unit.py Everything Looks Good!
> SUCCESS: /usr/local/p5dev/2buildout/src/plone.app.contentlisting/plone/app/contentlisting/tests/test_integration_doctest.py Everything Looks Good!
> SUCCESS: /usr/local/p5dev/2buildout/src/plone.app.contentlisting/plone/app/contentlisting/tests/base.py Everything Looks Good!
> root@debian:/usr/local/p5dev/2buildout/src/plone.app.contentlisting# 

.isort.cfg in the project path as well as ~/.isort.cfg match the documented config exactly.

**Comment by gforcada** [comment]
@fgrcon so if you run isort and changes the files, what are the changes being made? a ``git diff`` will be enough to check that

**Comment by fgrcon** [comment]
the diff is here: https://github.com/plone/plone.app.contentlisting/commit/ee5e70b2ab58459d5ccf899ce78201d15f4c5d70
Isort worked correctly ?  So whats wrong now ?

**Comment by gforcada** [comment]
No, it didn't work correctly, the proper sorting is:

```
from X import Y
from X import Y  # no blank lines in between
from X import Y

import X
import Y
```

**Pull request merged**
